name: vitmo_model_tester
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2
  tflite: ^1.0.2
  path_provider: ^0.5.0+1
  permission_handler: ^3.2.2
  provider: ^2.0.1
  camera: ^0.5.2+1
  image: ^2.1.4
  fab_dialer: ^0.1.3
  sqflite: ^1.1.6
  path: 
  charts_flutter: ^0.8.0
  stats: ^0.2.0+3
  auto_size_text: ^2.1.0
  csv: ^4.0.3
  flutter_email_sender: ^2.0.3
  flutter_mailer: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/dragon_mini_16_48_86.tflite
   - assets/dragon_mini_32_48_95.tflite
   - assets/dragon_mini_32_48_97.tflite
   - assets/dragon_labels_33.txt
   - assets/hardie_01.tflite
   - assets/hardie_02_48_99.tflite
   - assets/ed_97_48_1.tflite
   - assets/Resnet_20.tflite
   - assets/Resnet20_0_to_20.tflite
   - assets/Resnet20_BatchFirst.tflite
   - assets/images/IMG_01.png
   - assets/images/IMG_02.png
   - assets/images/IMG_03.png
   - assets/images/IMG_04.png
   - assets/images/IMG_05.png
   - assets/images/IMG_06.png
